### ISSUE TITLE
Support chat link doesn't work

### ISSUE THREAD

**Issue by zukka77** [datamachine/twx.botapi#14] opened 2015-11-03 07:13 UTC
It says the invitation link is expired here's the error:

Method: messages.checkChatInvite
Result: {"_":"rpc_error","error_code":400,"error_message":"INVITE_HASH_EXPIRED"}
Stack: h/u@https://web.telegram.org/js/app.js:18:3659
h/_/<@https://web.telegram.org/js/app.js:18:4931
l@https://web.telegram.org/js/app.js:8:11738
c/<@https://web.telegram.org/js/app.js:8:11910
fi/this.$get</m.prototype.$eval@https://web.telegram.org/js/app.js:8:19312
fi/this.$get</m.prototype.$digest@https://web.telegram.org/js/app.js:8:17739
fi/this.$get</m.prototype.$apply@https://web.telegram.org/js/app.js:8:19594
o/c<@https://web.telegram.org/js/app.js:8:26928
a@https://web.telegram.org/js/app.js:7:2843
on/u.defer/n<@https://web.telegram.org/js/app.js:7:4299
n@https://web.telegram.org/js/app.js:2:17042

**Comment by f-ewald** [comment] 2015-11-24 17:34
Same here for me.

**Comment by llybin** [comment] 2015-11-24 22:28
Have you checked in a mobile applications(or PC version)? Is it works fine?

**Comment by f-ewald** [comment] 2015-11-24 22:29
I checked with the web version as a logged in user.

**Comment by llybin** [comment] 2015-11-24 22:39
Guys, this is a problem web version. Close this issue. Open there: https://github.com/zhukov/webogram/issues

**Comment by f-ewald** [comment] 2015-11-24 22:48
Ok, I'll post there.

Edit: See: https://github.com/zhukov/webogram/issues/978

**Comment by f-ewald** [comment] 2015-11-25 19:30
Now it seems like the links is invalid since it doesn't open on iOS as well.

**Comment by llybin** [comment] 2015-11-25 19:44
What you do? Show please the code

**Comment by f-ewald** [comment] 2015-11-25 21:20
I just clicked on the link in the readme file in this repository. Nothing else :smile:

**Comment by llybin** [comment] 2015-11-25 21:39
:D Ok, close please this issue: zhukov/webogram#978 :D
Need to change the topic :D The links located in readme are invalid.

```
You can join our support chat at: https://telegram.me/joinchat/05c5c2f60112fa104d1c0c563b2fd34a
or our dev chat at: https://telegram.me/joinchat/05c5c2f6018bd6653eb6bbdccb7106a8
```

**Comment by FichteFoll** [comment] 2015-11-25 21:53
Doesn't open on desktop client (Windows) either, although I'm already in it: 
![2015-11-25_22 52 52](https://cloud.githubusercontent.com/assets/931051/11410398/5f9e930e-93c7-11e5-804e-c285c5445f5b.png)

Pretty much confirmed broken.

**Comment by Surye** [comment] 2015-11-30 21:29
We were having spam and channel take over issues. Now that multi-admin and better spam controls are in place, we've updated the support link.

**Closed as completed by Surye** 2015-11-30 21:29 UTC
